import React,{useEffect} from 'react'

function UserReturn() {
     useEffect(() => {
        window.scrollTo(0, 0);
    }, []);
    return (
        <div className='  bg-stone-50 px-5'>
            <div className='pt-10'>
                <p className='text-4xl font-bold xl:px-10'>RETURNS, DAMAGES, AND RESTOCKING FEES</p>
            </div>

            <div className='px-5 pb-16 pt-5 lg:px-16 xl:px-32 space-y-4'>
                <p className='text-2xl text-orange-500 py-2'><span className='font-bold'>RETURN &</span> REFUND POICY</p>

                <div>
                    <p>Customers are required to peruse and understand the terms of our Return and Refund Policy. If you do not agree to these terms contained in our Return and Refund Policy, you are advised not to accept the Terms of Use and may forthwith leave and stop using U-Pack. The terms contained in this Return and Refund Policy shall be accepted without modification and you agree to be bound by the terms contained herein by initiating a request for purchase of Product(s) on U-Pack.</p>
                </div>

                <div className='space-y-4'>
                    <p className='font-bold text-lg'>Can I cancel or change my order after it has been placed?</p>
                    <p>Orders may only be canceled within a limited time frame of being placed, typically within a few hours. Once an order is submitted, it is promptly sent for processing and cannot be altered. Any promo or discount codes must be applied at the time of order and cannot be retroactively added. If an order is canceled after it has been shipped, a restocking fee and return shipping charges will apply.</p>
                </div>

                <div className='space-y-4'>
                    <p className='font-bold text-lg'>To return a product ordered from U-Pack, just follow the below procedure:</p>
                    <p>You may return an unopened & undamaged item (s) in its original packaging, within 7 days of shipment receipt, for a full refund. Custom-printed orders are non-returnable due to their personalized nature.</p>

                    <div>
                        If U-Pack is at fault, we will arrange free return shipping. Otherwise, the customer is responsible for return shipping charges. The shelf life of our corrugated & cardboard boxes are subject to variation depending on environmental conditions including, but not limited to, humidity, temperature, and exposure to chemicals. Improper storage for extended periods can lead to degradation in strength and the appearance of white spots. Products are subject to industry tolerances. For instance, our boxes may show slight shade variations between batches, and a standard manufacturing tolerance of plus or minus 5 mm is considered standard. These variances do not qualify for returns. If you decide to return the goods for a reason other than manufacturing defect (e.g. you decided you did not need the item or ordered the wrong size), it will result in a 30% restocking fee and require you to pay for the shipping costs associated with returning the product(s) back to us.
                    </div>
                </div>

                <div>
                    <p className='py-4'>Why Do We Charge Restocking Fees?</p>
                    <ul className='list-disc px-7 space-y-4'>
                        <li>Returned items are handled and inspected by our warehouse team, which takes time away from their daily tasks.</li>
                        <li>Companies that don't charge restocking fees cover return costs by raising prices.</li>
                        <li>Many items that are returned cannot be resold and companies end up taking a loss.</li>
                    </ul>
                </div>

                <div>
                    <p>For items with manufacturing defects, please send them back for a full refund following our quality inspection. To initiate a return, email us to receive an RMA number and the return address. Ensure the item is securely packaged with the RMA number and original invoice, then send it to the address provided in our email. Please note, this policy does not apply to custom-printed orders, which are non-returnable.</p>
                </div>

                <div>
                    <p>Please do not return the product to the same courier person who delivers the order. An RMA number is compulsory to process returns. The same can be generated by sending us an email. To avoid any confusion or delays, our logistics partners are instructed to not accept a package as a return while performing a package delivery.</p>
                </div>

                <div className='space-y-4'>
                    <p className='font-bold text-lg'>If you receive a damaged item from U-Pack:</p>
                    <p>We take great care in packaging our products so they are transport-worthy. Nonetheless, if an item ordered by you on U-Pack was delivered in a damaged condition, please email us at sales@upack.in within 4 hours of material receipt along with multiple photographs of the unopened package illustrating the damage. We will contact the logistics partner and initiate a transit damage claim if applicable. Once the claim is approved and the material is received back to us, replacements will be sent out to you.</p>
                </div>

                <div className='space-y-4'>
                    <p className='font-bold text-lg'>Timeline and mode of refund:</p>
                    <p>Approved refunds are credited within 7-10 working days to the same payment option(s) originally used to make payment while placing the order.</p>
                </div>

                <div className='pt-10'>
                    <p>Last Updated: 20/10/2023</p>
                </div>

            </div>


        </div>
    )
}

export default UserReturn
